"""updated join

Revision ID: 351e3b3a4b00
Revises: f441cacb554f
Create Date: 2023-08-29 09:26:24.105942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351e3b3a4b00'
down_revision = 'f441cacb554f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_inventories_item_id_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventories_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_items_user_id_users', 'users', ['user_id'], ['id'])

    op.drop_table('inventories')
    # ### end Alembic commands ###
