"""empty message

Revision ID: 706a9e0e734a
Revises: 66d4a90d5a7f
Create Date: 2023-08-29 21:14:12.635999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706a9e0e734a'
down_revision = '66d4a90d5a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemcrates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_itemcrates_item_id_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_itemcrates_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inventoryitems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventoryitems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='fk_inventoryitems_item_id_items'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_inventoryitems_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('itemcrates')
    # ### end Alembic commands ###
