"""updated models

Revision ID: c6143df28b58
Revises: f58b5b4b333d
Create Date: 2023-08-27 18:06:22.555321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6143df28b58'
down_revision = 'f58b5b4b333d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
